### ISSUE TITLE
Should build-time env vars be moved to run-time?

### ISSUE THREAD

**Issue by ryanlovett** [the-commons-project/jupyterhealth-exchange#22]
The following environment variables need to be defined when building the container image:

 - `SITE_URL` (e.g. "http://localhost:8000")
 - `OIDC_CLIENT_AUTHORITY_PATH` (e.g. "/o/")
 - `OIDC_CLIENT_REDIRECT_URI_PATH` (e.g. "/auth/callback")
 
otherwise the container will fail to build. Can, or should, the variables be moved to run-time variables so that the container image can be built without them?

**Comment by s1monj** [comment]
Good idea - just added ticket
https://github.com/the-commons-project/jupyterhealth-exchange/issues/23
